### ISSUE TITLE
Failed to get practice problem: Social provider: auth0 is not defined in config

### ISSUE THREAD

**Issue by Ankit1010** [appirio-tech/arena-web#608]
Getting this error when trying to load practice problems. Happens on both Safari and Chrome, even after updating flash and clearing cookies.

**Comment by soon** [comment]
:+1:, same issue

**Comment by uacy** [comment]
++

**Comment by dstyvsky** [comment]
+=1

**Comment by chinmaybhusari** [comment]
same issue .Please resolve at the earliset. Thanks

**Comment by joynal** [comment]
Same issue.

**Comment by WrRan** [comment]
++

**Comment by L-Neo** [comment]
Same here

**Comment by prernabellara** [comment]
same here

**Comment by RuchaK** [comment]
+1

**Comment by elhafyani4** [comment]
same here

**Comment by avastu** [comment]
Same here

**Comment by warlockhjn** [comment]
same problem, did anyone solve it?

**Comment by ShaneSegal** [comment]
Same issues - running on Chrome v46 Windows 10

**Comment by jonbonJoeB** [comment]
Same. This is the API call that fails: "api.topcoder.com/v2/data/srm/practice/problems?sortColumn=problemName&sortOrder=asc&pageSize=10&pageIndex=1:1 GET https://api.topcoder.com/v2/data/srm/practice/problems?sortColumn=problemName&sortOrder=asc&pageSize=10&pageIndex=1 500 (Internal Server Error)"... It also may help to note that when visiting the Lobby/Dashboard, before clicking on Practice Problems link in the nav bar, there is another 500 Internal Server Error which is .... "TypeError: Cannot read property 'balloonGuides' of undefined
    at bundle.js:2491
    at bundle.js:38466
    at wrappedCallback (bundle.js:41977)
    at wrappedCallback (bundle.js:41977)
    at bundle.js:42063
    at Scope.$eval (bundle.js:43106)
    at Scope.$digest (bundle.js:42918)
    at Scope.$apply (bundle.js:43210)
    at done (bundle.js:38745)
    at completeRequest (bundle.js:38959)(anonymous function) @ bundle.js:40421(anonymous function) @ bundle.js:37693wrappedCallback @ bundle.js:41980wrappedCallback @ bundle.js:41977(anonymous function) @ bundle.js:42063Scope.$eval @ bundle.js:43106Scope.$digest @ bundle.js:42918Scope.$apply @ bundle.js:43210done @ bundle.js:38745completeRequest @ bundle.js:38959xhr.onreadystatechange @ bundle.js:38898nrWrapper @ newrelic.js:1
api.topcoder.com/v2/challenges/open?pageIndex=-1&sortColumn=registrationEndDate&sortOrder=asc:1 GET https://api.topcoder.com/v2/challenges/open?pageIndex=-1&sortColumn=registrationEndDate&sortOrder=asc 500 (Internal Server Error)
bundle.js:3868 error: {"error":{"name":"Internal Server Error","value":500,"description":"Something is broken. Please contact support.","details":"Social provider: auth0 is not defined in config"},"serverInformation":{"serverName":"TopCoder API","apiVersion":"0.0.1","requestDuration":1,"currentTime":1447210466907},"requesterInformation":{"id":"19fb996f9969d52594e0a69e76ca74009ae620bc-4Op0xu4HsgLOSWOe","remoteIP":"68.102.20.29","receivedParams":{"pageIndex":"-1","sortColumn":"registrationEndDate","sortOrder":"asc","apiVersion":"v2","action":"getOpenChallenges"}}}" -- that is with the 500 server error and the error that gets logged to the console by the app

**Comment by michaelbausor** [comment]
++

**Comment by Lucodivo** [comment]
++

**Comment by Ducky93** [comment]
Did we solve this issue? i have it atm after updating java to 8u77 and can't solve it since 2 days

**Comment by Dhruv-Jauhar** [comment]
Same here.
Chrome (64bit) Winodws 10

**Comment by qqpeter99** [comment]
same here on Mac chrome

**Comment by hmpandey** [comment]
+1
Windows Chrome

**Comment by shihab122** [comment]
same issue
